use std::collections::HashMap;

use anyhow::{Result, anyhow, bail};
mod control_flow;
mod fpu;
mod math;
mod misc;
mod mmx;
mod string;

use crate::{Block, BlockType, Instr, Module, State, memory::Memory, write_if_changed};

/// Preamble shared by the generated module and its parts.
const HEADER: &str = "//! this module was generated by tc

#![allow(unreachable_code)]
#![allow(unused_parens)]
#![allow(unused_variables)]
#![allow(non_snake_case)]

use runtime::*;
";

/// Preamble for a part file: everything the module file has in scope,
/// including its sibling parts, reaches it through `super`.
const PART_HEADER: &str = "//! this module was generated by tc

#![allow(unreachable_code)]
#![allow(unused_parens)]
#![allow(unused_variables)]
#![allow(non_snake_case)]

use super::*;
";

fn reg_name(r: iced_x86::Register) -> String {
    format!("{r:?}").to_ascii_lowercase()
}

fn instr_name(instr: &iced_x86::Instruction) -> String {
    if instr.mnemonic() == iced_x86::Mnemonic::Loop {
        return "loop_".to_string();
    }
    format!("{:?}", instr.mnemonic()).to_ascii_lowercase()
}

pub fn get_reg(r: iced_x86::Register) -> String {
    use iced_x86::Register::*;
    match r {
        EAX | ECX | EDX | EBX | ESI | EDI | ESP | EBP => {
            format!("ctx.cpu.regs.{reg}", reg = reg_name(r))
        }
        AL | AH | AX | CL | CH | CX | DL | DH | DX | BL | BH | BX |
        DI | SI | SP | BP | // comment to disable formatting
        CS | DS | ES | FS | GS | SS => {
            format!("ctx.cpu.regs.get_{reg}()", reg = reg_name(r))
        }
        r => todo!("{r:?}"),
    }
}

pub fn set_reg(r: iced_x86::Register, expr: String) -> String {
    use iced_x86::Register::*;
    match r {
        EAX | ECX | EDX | EBX | ESI | EDI | ESP | EBP => {
            format!("ctx.cpu.regs.{reg} = {expr};", reg = reg_name(r))
        }
        AL | AH | AX | CL | CH | CX | DL | DH | DX | BL | BH | BX |
        DI | SI | SP | BP | // comment to disable formatting
        CS | DS | ES | FS | GS | SS => {
            format!("ctx.cpu.regs.set_{reg}({expr});", reg = reg_name(r))
        }
        r => todo!("{r:?}"),
    }
}

impl<'a> CodeGen<'a> {
    /// Code generate a memory address reference.
    pub fn gen_addr_offset(&self, instr: &iced_x86::Instruction) -> String {
        use iced_x86::Register::*;
        let mut expr = Vec::new();
        if !self.module.segment_addressed() {
            // 16-bit segments handled in gen_addr(), not here
            match instr.memory_segment() {
                CS | DS | ES | GS | SS => {}
                FS => expr.push(format!("ctx.cpu.regs.fs_base")),
                None => {}
                r => todo!("{r:?} in {instr}"),
            }
        }
        match instr.memory_base() {
            None => {}
            r => expr.push(get_reg(r)),
        }
        if instr.memory_index() != None {
            if instr.memory_index_scale() != 1 {
                expr.push(format!(
                    "({}*{})",
                    get_reg(instr.memory_index()),
                    instr.memory_index_scale()
                ));
            } else {
                expr.push(format!("{}", get_reg(instr.memory_index()),));
            }
        }
        let offset = instr.memory_displacement32();
        if offset != 0 || expr.is_empty() {
            expr.push(format!("{offset:#x}u{}", self.module.bitness()));
        }

        expr.into_iter()
            .enumerate()
            .map(|(i, e)| {
                if i == 0 {
                    format!("{e}")
                } else {
                    format!(".wrapping_add({e})")
                }
            })
            .collect::<Vec<_>>()
            .join("")
    }

    /// Codegen the absolute address found in an instruction that has a memory reference.
    /// Even for 16-bit code we generate a 32-bit memory address, because the computed
    /// address can go beyond a 16-bit address range.
    pub fn gen_addr(&self, instr: &iced_x86::Instruction) -> String {
        let addr = self.gen_addr_offset(instr);
        if self.module.segment_addressed() {
            // The above offset expression will be a u16 in real mode.
            // Convert to u32 as we add the segment.
            format!(
                "segofs(ctx.cpu.regs.get_{seg}(), {addr})",
                seg = reg_name(instr.memory_segment())
            )
        } else {
            addr
        }
    }
}

pub fn get_mem(typ: String, addr: String) -> String {
    format!("ctx.memory.read::<{typ}>({addr})")
}

pub fn set_mem(typ: String, addr: String, expr: String) -> String {
    format!("ctx.memory.write::<{typ}>({addr}, {expr});")
}

impl<'a> CodeGen<'a> {
    pub fn get_op(&self, instr: &iced_x86::Instruction, n: u32) -> String {
        use iced_x86::OpKind::*;
        match instr.op_kind(n) {
            Immediate8 => format!("{:#x}u8", instr.immediate8()),
            Immediate16 => format!("{:#x}u16", instr.immediate16()),
            Immediate8to16 => format!("{:#x}u16", instr.immediate8to16()),
            Immediate8to32 => format!("{:#x}u32", instr.immediate8to32()),
            Immediate32 => format!("{:#x}u32", instr.immediate32()),
            Register => get_reg(instr.op_register(n)),
            Memory => get_mem(format!("u{}", mem_size(instr)), self.gen_addr(instr)),
            k => todo!("{:?}", k),
        }
    }
}

pub fn reg_size(r: iced_x86::Register) -> usize {
    use iced_x86::Register::*;
    match r {
        AL | AH | BL | BH | CL | CH | DL | DH => 8,
        AX | BX | CX | DX | SI | DI | BP | SP => 16,
        CS | DS | ES | FS | GS | SS => 16,
        EAX | EBX | ECX | EDX | ESI | EDI | ESP | EBP => 32,
        MM0 | MM1 | MM2 | MM3 | MM4 | MM5 | MM6 | MM7 => 64,
        r => todo!("{r:?}"),
    }
}

pub fn mem_size(instr: &iced_x86::Instruction) -> usize {
    use iced_x86::MemorySize::*;
    match instr.memory_size() {
        UInt8 | Int8 => 8,
        UInt16 | Int16 => 16,
        UInt32 | Int32 => 32,
        UInt64 | Int64 => 64,
        Float32 => 32,
        Float64 => 64,
        Float80 => 80,
        Packed32_UInt8 => 32,
        Packed64_UInt8 | Packed64_Int8 | Packed64_UInt16 | Packed64_Int16 | Packed64_UInt32
        | Packed64_Int32 => 64,
        DwordOffset => 32, // e.g. `call dword ptr [...]`
        s => todo!("{s:?}"),
    }
}

pub fn op_size(instr: &iced_x86::Instruction, n: u32) -> usize {
    use iced_x86::OpKind::*;
    match instr.op_kind(n) {
        Register => reg_size(instr.op_register(n)),
        Memory => mem_size(instr),
        Immediate16 => 16,
        Immediate8to16 => 16,
        Immediate8to32 => 32,
        Immediate32 => 32,
        k => todo!("{k:?}"),
    }
}

impl<'a> CodeGen<'a> {
    pub fn set_op(&self, instr: &iced_x86::Instruction, n: u32, expr: String) -> String {
        use iced_x86::OpKind::*;
        match instr.op_kind(n) {
            Register => set_reg(instr.op_register(n), expr),
            Memory => {
                let addr = self.gen_addr(instr);
                let size = mem_size(instr);
                set_mem(format!("u{size}"), addr, expr)
            }
            k => todo!("{:?}", k),
        }
    }
}

pub struct CodeGen<'a> {
    module: &'a Module,
    mem: &'a Memory,
    blocks: &'a HashMap<u32, Block>,
    trace: bool,
    /// Statically-known jump targets with no discovered block; each gets a
    /// panicking stub function so the output still compiles and runs.
    unknown: std::collections::BTreeSet<u32>,
    /// Output buffer.
    buf: String,
}

impl<'a> CodeGen<'a> {
    pub fn new(state: &'a State, trace: bool) -> Self {
        Self {
            module: &state.module,
            mem: &state.mem,
            blocks: &state.blocks,
            trace,
            unknown: Default::default(),
            buf: Default::default(),
        }
    }

    fn line(&mut self, s: impl AsRef<str>) {
        self.buf.push_str(s.as_ref());
        self.buf.push('\n');
    }

    /// Codegen a Cont expression for a jump to a statically known address.
    /// Safe to evaluate in argument position: an unknown target resolves to a
    /// stub that only panics once actually jumped to.
    pub fn resolve_cont(&mut self, addr: u32) -> String {
        if let Some(block) = self.blocks.get(&addr) {
            format!("Cont({})", block.name())
        } else {
            log::warn!("static jmp to unknown block {addr:08x}");
            self.unknown.insert(addr);
            format!("Cont(unk_{addr:x})")
        }
    }

    fn todo(&mut self, msg: String) {
        self.line(format!("todo!({msg:?});"));
    }

    fn gen_block(&mut self, block: &Block) {
        match &block.ty {
            BlockType::Instrs(instrs) => {
                self.line(format!(
                    "pub fn {name}(ctx: &mut Context) -> Cont {{",
                    name = block.name()
                ));
                // self.line(format!("println!(\"{name}\");", name = block.name()));
                for instr in instrs {
                    if self.trace {
                        match self.module {
                            Module::DOS(_) => {
                                self.line(format!("ctx.dump_dosbox({:#x});", instr.iced.ip32()));
                            }
                            Module::Windows(_) => todo!(),
                        }
                    }
                    if let Err(e) = self.gen_instr(instr) {
                        self.line(format!("panic!({:?});", e.to_string()));
                        break;
                    }
                }

                let last = instrs.last().unwrap();
                if last.iced.flow_control() == iced_x86::FlowControl::Next
                    || (last.iced.mnemonic() == iced_x86::Mnemonic::Call && last.hint.is_some())
                {
                    let cont = self.resolve_cont(last.next_ip().to_addr());
                    self.line(cont);
                }

                self.line("}\n");
            }
            BlockType::Stdcall(_) | BlockType::Extern(_) => {
                // no emit
            }
        }
    }

    fn gen_instr(&mut self, instr: &Instr) -> anyhow::Result<()> {
        // log::info!("gen: {:08x} {}", instr.iced.ip32(), instr.iced);
        self.line(format!("// {} {}", instr.ip, instr.iced));
        if self.codegen_control_flow(instr) {
        } else if self.codegen_math(&instr.iced) {
        } else if self.codegen_string(&instr.iced) {
        } else if self.codegen_misc(&instr.iced) {
        } else if self.codegen_fpu(&instr.iced) {
        } else if self.codegen_mmx(&instr.iced) {
        } else {
            anyhow::bail!("{:?} not implemented", instr.iced.mnemonic());
        }
        Ok(())
    }

    fn gen_init(&mut self) {
        // It would be cool if we could just link a wasm object file that contains data sections
        // like
        //   (data (i32.const 0x400000) "....")
        // Unfortunately, wasm-lld only supports "relocatable" object files which means it moves
        // the location of such data at link time.  We could do it by postprocessing the wasm
        // file, maybe.

        self.line("fn init(regs: &mut runtime::Regs, memory: &mut runtime::Memory, mappings: &mut runtime::Mappings) {");

        for map in self.mem.mappings.vec().iter() {
            let addr = map.addr;
            let buf = self.mem.slice(map.addr, map.size);
            let zeroed = buf.iter().all(|&b| b == 0);

            self.line(format!(
                "mappings.reserve(runtime::Mapping {{
                    desc: {desc:?}.to_string(),
                    addr: {addr:#x},
                    size: {size:#x},
                    section: {section},
                }});",
                desc = map.desc,
                size = buf.len(),
                section = map.section,
            ));
            if !zeroed {
                self.line(format!(
                    "let bytes = include_bytes!(\"../data/{addr:08x}.raw\").as_slice();
let out = &mut memory.bytes[{addr:#x}..][..bytes.len()];
out.copy_from_slice(bytes);",
                ));
            }
        }

        match self.module {
            Module::Windows(module) => {
                if !module.vtables.is_empty() {
                    self.line("unsafe {");
                    for (module, val) in &module.vtables {
                        self.line(format!("winapi::{module}::VTABLE = {val:#x};"));
                    }
                    self.line("}");
                }
                let mut modules = Vec::new();
                for import in &module.imports {
                    if !modules.contains(&import.dll) {
                        modules.push(import.dll.clone());
                    }
                }
                for dll in modules {
                    self.line(format!("winapi::kernel32::register_module({dll:?});"));
                }
                for (dll, func) in &module.dynamic_exports {
                    let addr = module
                        .imports
                        .iter()
                        .find(|imp| crate::same_dll(&imp.dll, dll) && imp.func == *func)
                        .expect("dynamic export without a reserved address")
                        .addr;
                    self.line(format!(
                        "winapi::kernel32::register_export({dll:?}, {func:?}, {addr:#x});"
                    ));
                }
            }
            Module::DOS(module) => {
                self.line(format!("
regs.cs = {load_segment:#x};
regs.ds = {psp_segment:#x}; // PSP
regs.es = {psp_segment:#x}; // PSP
regs.ss = {stack_segment:#x};
// initial cx: https://stackoverflow.com/questions/79440940/why-cx-register-already-has-a-non-zero-value-on-startup-of-a-dos-program-unlike
regs.ecx = 0xff;
regs.esp = {stack_pointer:#x};
",
                    load_segment = module.load_segment,
                    psp_segment = module.psp_segment,
                    stack_segment = module.stack_segment,
                    stack_pointer = module.stack_pointer,
                ));
                if module.is_com {
                    self.line("regs.esp = 0xfffe;");
                } else {
                    self.line(format!(
                        "regs.edx = {:#x}; // PSP segment",
                        module.psp_segment
                    ));

                    self.line(
                        "
                        // arbitrary values, matching dosbox
                        regs.esi = 0x68e;
                        regs.edi = 0x800;
                        regs.ebp = 0x91c;
                        ",
                    );
                }
            }
        }

        self.line("}");
        self.line("");
    }

    /// Emit the block functions, split across `generated/part_NN.rs` files
    /// once there are enough of them.
    ///
    /// rustc's time on one module grows worse than linearly, and a large
    /// program's blocks would otherwise land in a single ten-megabyte file that
    /// has to be reparsed in full on every rebuild. Returns the part names, or
    /// an empty list when everything fit in the module file itself.
    fn gen_blocks(&mut self, outdir: &str) -> Result<Vec<String>> {
        /// Split once a part reaches roughly this size. Small programs stay in
        /// a single file, which keeps their generated output easy to read.
        /// Stay under 1mb because that is the largest size Jujutsu wants to track.
        const MAX_PART_BYTES: usize = 512 << 10;

        let mut addrs = self.blocks.keys().copied().collect::<Vec<_>>();
        addrs.sort();

        // Generate every block into one buffer first, remembering where each
        // one starts so parts can be cut at function boundaries.
        let module_buf = std::mem::take(&mut self.buf);
        let mut boundaries = vec![0usize];
        for &addr in &addrs {
            let block = self.blocks.get(&addr).unwrap();
            self.gen_block(&block);
            boundaries.push(self.buf.len());
        }
        for addr in self.unknown.iter().copied().collect::<Vec<_>>() {
            self.line(format!(
                "pub fn unk_{addr:x}(_ctx: &mut Context) -> Cont {{
    runtime::unknown_block({addr:#x})
}}\n"
            ));
            boundaries.push(self.buf.len());
        }
        let blocks_text = std::mem::replace(&mut self.buf, module_buf);

        if blocks_text.len() <= MAX_PART_BYTES {
            self.buf.push_str(&blocks_text);
            self.gen_blocks_table(&addrs);
            return Ok(Vec::new());
        }

        // Cut at the first block boundary past each part's size limit.
        std::fs::create_dir_all(format!("{outdir}/src/generated"))?;
        let mut parts = Vec::new();
        let mut start = 0;
        while start < blocks_text.len() {
            let target = start + MAX_PART_BYTES;
            let end = match boundaries.iter().find(|&&b| b >= target) {
                Some(&end) => end,
                None => blocks_text.len(),
            };
            let name = format!("part_{:02}", parts.len());
            let path = format!("{outdir}/src/generated/{name}.rs");
            let text = format!("{}\n{}", PART_HEADER, &blocks_text[start..end]);
            write_if_changed(&path, rustfmt(&text)?.as_bytes())
                .map_err(|err| anyhow!("write {path}: {err}"))?;
            parts.push(name);
            start = end;
        }

        for name in &parts {
            self.line(format!("mod {name};"));
            self.line(format!("pub use {name}::*;"));
        }
        self.line("");
        self.gen_blocks_table(&addrs);
        Ok(parts)
    }

    fn gen_blocks_table(&mut self, addrs: &[u32]) {
        self.line(format!(
            "const BLOCKS: [(u32, ContFn); {}] = [\n",
            addrs.len() + 1,
        ));

        for &addr in addrs {
            let block = self.blocks.get(&addr).unwrap();
            self.line(format!("({addr:#x}, {name}),", name = block.name()));
        }
        match self.module {
            Module::Windows(_) => {
                self.line("(runtime::RETURN_FROM_X86_ADDR32, Context::return_from_x86),");
            }
            Module::DOS(_) => {
                self.line("(runtime::RETURN_FROM_X86_ADDR16.abs(), Context::return_from_x86),");
            }
        }
        self.line("];");
        self.line("");
    }

    pub fn gen_file(&mut self, outdir: &str) -> Result<()> {
        self.line(HEADER);
        if self.module.is_windows() {
            self.line("use winapi::*;");
        }

        self.gen_init();

        let parts = self.gen_blocks(outdir)?;

        // TODO: split EXEDATA into DOS/Windows.
        let resources = match self.module {
            Module::DOS(_) => 0..0,
            Module::Windows(m) => m.resources.clone().unwrap_or(0..0),
        };

        let entry_point = self.module.entry_point().to_addr();
        let entry_point = self
            .blocks
            .get(&entry_point)
            .ok_or_else(|| anyhow!("entry point {entry_point:x} not found in parsed blocks"))?;
        self.line(format!(
            "pub const EXEDATA: EXEData = EXEData {{
            image_base: {image_base:#x},
            resources: {res_start:#x}..{res_end:#x},
            blocks: &BLOCKS,
            init,
            entry_point: Cont({entry_point}),
        }};\n\n",
            image_base = self.module.image_base(),
            res_start = resources.start,
            res_end = resources.end,
            entry_point = entry_point.name(),
        ));

        std::fs::create_dir_all(format!("{outdir}/src"))?;
        let path = format!("{outdir}/src/generated.rs");
        let text = rustfmt(&self.buf)?;
        write_if_changed(&path, text.as_bytes()).map_err(|err| anyhow!("write {path}: {err}"))?;

        // Drop parts left over from a previous run that produced more of them,
        // which would otherwise fail to compile against the current output.
        if let Ok(entries) = std::fs::read_dir(format!("{outdir}/src/generated")) {
            for entry in entries.flatten() {
                let name = entry.file_name().to_string_lossy().to_string();
                let Some(stem) = name.strip_suffix(".rs") else {
                    continue;
                };
                if stem.starts_with("part_") && !parts.iter().any(|part| part == stem) {
                    std::fs::remove_file(entry.path())?;
                }
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn mem_size_handles_float80() {
        let bytes = [0xdb, 0x28];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = decoder.decode();
        assert_eq!(instr.memory_size(), iced_x86::MemorySize::Float80);
        assert_eq!(super::mem_size(&instr), 80);
    }

    #[test]
    fn codegen_handles_float80_load_and_store() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);

        for (bytes, want) in [
            (
                [0xdb, 0x28],
                "ctx.memory.read::<F80>(ctx.cpu.regs.eax).to_f64()",
            ),
            (
                [0xdb, 0x38],
                "ctx.memory.write::<F80>(ctx.cpu.regs.eax, F80::from_f64(ctx.cpu.fpu.get(0)))",
            ),
        ] {
            let mut decoder =
                iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
            let instr = crate::Instr {
                ip: crate::IP::Flat(0),
                iced: decoder.decode(),
                hint: None,
            };
            codegen.gen_instr(&instr).unwrap();
            assert!(codegen.buf.contains(want));
        }
    }

    #[test]
    fn codegen_handles_bit_operations() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);

        for (bytes, want) in [
            (
                &[0x0f, 0xa3, 0xc8][..],
                "bt(ctx.cpu.regs.eax, bit, &mut ctx.cpu.flags);",
            ),
            (
                &[0x0f, 0xab, 0xc8][..],
                "ctx.cpu.regs.eax = bts(ctx.cpu.regs.eax, bit, &mut ctx.cpu.flags);",
            ),
            (
                &[0x0f, 0xba, 0x28, 0x03][..],
                "ctx.memory.write::<u32>(addr, bts(value, bit, &mut ctx.cpu.flags));",
            ),
        ] {
            let mut decoder =
                iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
            let instr = crate::Instr {
                ip: crate::IP::Flat(0),
                iced: decoder.decode(),
                hint: None,
            };
            codegen.gen_instr(&instr).unwrap();
            assert!(codegen.buf.contains(want));
        }
    }

    #[test]
    fn codegen_uses_signed_offsets_for_memory_bit_indices() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x0f, 0xa3, 0x08];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();

        assert!(
            codegen
                .buf
                .contains("ctx.cpu.regs.eax.wrapping_add((((bit as i32 >> 5) * 4i32) as u32))")
        );
    }

    #[test]
    fn codegen_handles_16_bit_double_shifts() {
        let mut state = crate::State::default();
        state.module = crate::Module::DOS(crate::DOSModule::default());
        let mut codegen = super::CodeGen::new(&state, false);

        for (bytes, want) in [
            (
                &[0x0f, 0xa4, 0xd8, 0x01][..],
                "shld16(ctx.cpu.regs.get_ax()",
            ),
            (
                &[0x0f, 0xac, 0xd8, 0x01][..],
                "shrd16(ctx.cpu.regs.get_ax()",
            ),
        ] {
            let mut decoder =
                iced_x86::Decoder::with_ip(16, bytes, 0, iced_x86::DecoderOptions::NONE);
            let instr = crate::Instr {
                ip: crate::IP::Seg((0, 0).into()),
                iced: decoder.decode(),
                hint: None,
            };
            codegen.gen_instr(&instr).unwrap();
            assert!(codegen.buf.contains(want));
        }
    }

    #[test]
    fn codegen_handles_packed_add_sub() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);

        for (bytes, want) in [
            ([0x0f, 0xfc, 0xc1], "paddb"),
            ([0x0f, 0xfd, 0xc1], "paddw"),
            ([0x0f, 0xfe, 0xc1], "paddd"),
            ([0x0f, 0xf8, 0xc1], "psubb"),
            ([0x0f, 0xfa, 0xc1], "psubd"),
            ([0x0f, 0xe8, 0xc1], "psubsb"),
            ([0x0f, 0xe9, 0xc1], "psubsw"),
        ] {
            let mut decoder =
                iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
            let instr = crate::Instr {
                ip: crate::IP::Flat(0),
                iced: decoder.decode(),
                hint: None,
            };

            codegen.gen_instr(&instr).unwrap();
            assert!(codegen.buf.contains(want));
        }
    }

    #[test]
    fn codegen_handles_mmx_memory_widths() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);

        for opcode in [0xfc, 0xfd, 0xfe, 0xf8, 0xfa, 0xe8, 0xe9] {
            let bytes = [0x0f, opcode, 0x00];
            let mut decoder =
                iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
            let instr = crate::Instr {
                ip: crate::IP::Flat(0),
                iced: decoder.decode(),
                hint: None,
            };

            codegen.gen_instr(&instr).unwrap();
            assert!(
                codegen
                    .buf
                    .contains("ctx.memory.read::<u64>(ctx.cpu.regs.eax)")
            );
        }
    }

    #[test]
    fn codegen_handles_port_io() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);

        for (bytes, want) in [
            (
                &[0xec][..],
                "ctx.cpu.regs.set_al(port_in(ctx.cpu.regs.get_dx(), 8) as u8);",
            ),
            (
                &[0xe7, 0x80][..],
                "port_out(0x80u16, (ctx.cpu.regs.eax) as u32, 32);",
            ),
        ] {
            let mut decoder =
                iced_x86::Decoder::with_ip(32, bytes, 0, iced_x86::DecoderOptions::NONE);
            let instr = crate::Instr {
                ip: crate::IP::Flat(0),
                iced: decoder.decode(),
                hint: None,
            };
            codegen.gen_instr(&instr).unwrap();
            assert!(codegen.buf.contains(want));
        }
    }

    #[test]
    fn codegen_handles_protected_mode_segment_loads() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xc4, 0x00];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("let ptr_offset = ctx.memory.read::<u32>(ctx.cpu.regs.eax);")
        );
        assert!(codegen.buf.contains(
            "let ptr_segment = ctx.memory.read::<u16>(ctx.cpu.regs.eax.wrapping_add(4u32));"
        ));
        assert!(codegen.buf.contains("ctx.cpu.regs.es = ptr_segment;"));
        assert!(codegen.buf.contains("ctx.cpu.regs.eax = ptr_offset;"));
        assert!(!codegen.buf.contains("todo!"));
    }

    #[test]
    fn codegen_reads_six_byte_protected_segment_pointers() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xc4, 0x00];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();

        assert!(
            codegen
                .buf
                .contains("let ptr_offset = ctx.memory.read::<u32>(ctx.cpu.regs.eax);")
        );
        assert!(codegen.buf.contains(
            "let ptr_segment = ctx.memory.read::<u16>(ctx.cpu.regs.eax.wrapping_add(4u32));"
        ));
        assert!(codegen.buf.contains("ctx.cpu.regs.es = ptr_segment;"));
        assert!(codegen.buf.contains("ctx.cpu.regs.eax = ptr_offset;"));
        assert!(
            !codegen
                .buf
                .contains("ctx.memory.read::<u64>(ctx.cpu.regs.eax)")
        );
    }

    #[test]
    fn codegen_registers_statically_imported_modules() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule {
            imports: vec![
                crate::Import {
                    dll: "KERNEL32".into(),
                    func: "GetLastError".into(),
                    iat_addr: 0x1000,
                    addr: 0,
                    data: false,
                },
                crate::Import {
                    dll: "KERNEL32".into(),
                    func: "SetLastError".into(),
                    iat_addr: 0x1004,
                    addr: 0,
                    data: false,
                },
                crate::Import {
                    dll: "USER32".into(),
                    func: "GetActiveWindow".into(),
                    iat_addr: 0x1008,
                    addr: 0,
                    data: false,
                },
                crate::Import {
                    dll: "KERNEL32.DLL".into(),
                    func: "IsProcessorFeaturePresent".into(),
                    iat_addr: 0x100c,
                    addr: 0xfafbfc00,
                    data: false,
                },
            ],
            dynamic_exports: vec![("kernel32".into(), "IsProcessorFeaturePresent".into())],
            ..Default::default()
        });
        let mut codegen = super::CodeGen::new(&state, false);

        codegen.gen_init();

        assert_eq!(
            codegen
                .buf
                .matches("winapi::kernel32::register_module(\"KERNEL32\");")
                .count(),
            1
        );
        assert!(
            codegen
                .buf
                .contains("winapi::kernel32::register_module(\"USER32\");")
        );
        assert!(codegen.buf.contains(
            "winapi::kernel32::register_export(\"kernel32\", \"IsProcessorFeaturePresent\", 0xfafbfc00);"
        ));
    }

    #[test]
    fn codegen_uses_16_bit_segmented_addresses() {
        let state = crate::State::default();
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x8b, 0x44, 0x10];
        let mut decoder = iced_x86::Decoder::with_ip(16, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Seg((0, 0).into()),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains(
            "ctx.memory.read::<u16>(segofs(ctx.cpu.regs.get_ds(), ctx.cpu.regs.get_si().wrapping_add(0x10u16)))"
        ));
    }

    #[test]
    fn codegen_handles_segptr32_indirect_calls() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xff, 0x59, 0xc3];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        assert_eq!(instr.iced.memory_size(), iced_x86::MemorySize::SegPtr32);
        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.memory.read::<u32>(ctx.cpu.regs.ecx.wrapping_add(0xffffffc3u32))")
        );
        assert!(
            codegen
                .buf
                .contains("ctx.callf32(0x3, seg, ctx.indirect32(addr))")
        );
    }

    #[test]
    fn codegen_handles_32_bit_far_branches() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);

        for (bytes, want) in [
            (
                &[0xea, 0x78, 0x56, 0x34, 0x12, 0x1b, 0x00][..],
                "ctx.cpu.regs.cs = 0x1b;",
            ),
            (
                &[0x9a, 0x78, 0x56, 0x34, 0x12, 0x1b, 0x00][..],
                "ctx.callf32(0x7, 0x1b, Cont(unk_12345678))",
            ),
        ] {
            let mut decoder =
                iced_x86::Decoder::with_ip(32, bytes, 0, iced_x86::DecoderOptions::NONE);
            let instr = crate::Instr {
                ip: crate::IP::Flat(0),
                iced: decoder.decode(),
                hint: None,
            };
            codegen.gen_instr(&instr).unwrap();
            assert!(codegen.buf.contains(want));
        }
    }

    #[test]
    fn codegen_uses_instruction_operand_size_for_rets() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);

        for (bytes, want) in [
            (&[0xc3][..], "ctx.ret32(0)"),
            (&[0x66, 0xc3][..], "ctx.ret16(0)"),
            (&[0xc2, 0x04, 0x00][..], "ctx.ret32(4)"),
            (&[0x66, 0xc2, 0x04, 0x00][..], "ctx.ret16(4)"),
            (&[0xcb][..], "ctx.retf32(0)"),
            (&[0x66, 0xcb][..], "ctx.retf16(0)"),
            (&[0xcf][..], "ctx.iret32()"),
            (&[0x66, 0xcf][..], "ctx.iret16()"),
        ] {
            codegen.buf.clear();
            let mut decoder =
                iced_x86::Decoder::with_ip(32, bytes, 0, iced_x86::DecoderOptions::NONE);
            let instr = crate::Instr {
                ip: crate::IP::Flat(0),
                iced: decoder.decode(),
                hint: None,
            };

            codegen.gen_instr(&instr).unwrap();
            assert!(
                codegen.buf.contains(want),
                "wanted {want:?} in {:?}",
                codegen.buf
            );
        }
    }

    #[test]
    fn codegen_handles_16_bit_operand_control_flow() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);

        for (bytes, wants) in [
            // call rel16
            (
                &[0x66, 0xe8, 0x34, 0x12][..],
                vec!["ctx.call16(", "Cont(unk_1238)"],
            ),
            // call ax
            (
                &[0x66, 0xff, 0xd0][..],
                vec!["ctx.call16(", "ctx.indirect(ctx.cpu.regs.get_ax() as u32)"],
            ),
            // call word ptr [eax]
            (
                &[0x66, 0xff, 0x10][..],
                vec!["ctx.call16(", "ctx.indirect(addr as u32)"],
            ),
            // jmp word ptr [eax]
            (&[0x66, 0xff, 0x20][..], vec!["ctx.indirect(addr as u32)"]),
            // jmp ax
            (
                &[0x66, 0xff, 0xe0][..],
                vec!["ctx.indirect(ctx.cpu.regs.get_ax() as u32)"],
            ),
            // call far ptr16:16
            (
                &[0x66, 0x9a, 0x78, 0x56, 0x1b, 0x00][..],
                vec!["ctx.callf16(", "0x1b"],
            ),
        ] {
            codegen.buf.clear();
            let mut decoder =
                iced_x86::Decoder::with_ip(32, bytes, 0, iced_x86::DecoderOptions::NONE);
            let instr = crate::Instr {
                ip: crate::IP::Flat(0),
                iced: decoder.decode(),
                hint: None,
            };

            codegen.gen_instr(&instr).unwrap();
            for want in wants {
                assert!(
                    codegen.buf.contains(want),
                    "wanted {want:?} in {:?}",
                    codegen.buf
                );
            }
        }
    }

    #[test]
    fn codegen_handles_fabs() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd9, 0xe1];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.fpu.set(0, ctx.cpu.fpu.get(0).abs());")
        );
    }

    #[test]
    fn codegen_handles_f2xm1() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd9, 0xf0];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.fpu.set(0, ctx.cpu.fpu.get(0).exp2() - 1.0);")
        );
    }

    #[test]
    fn codegen_handles_fnstenv() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd9, 0x30];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.fpu.store_env(&mut ctx.memory, ctx.cpu.regs.eax);")
        );
    }

    #[test]
    fn codegen_handles_fldenv() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd9, 0x20];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.fpu.load_env(&ctx.memory, ctx.cpu.regs.eax);")
        );
    }

    #[test]
    fn codegen_handles_fnsave_and_frstor() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);

        for (bytes, want) in [
            (
                [0xdd, 0x30],
                "ctx.cpu.fpu.save(&mut ctx.memory, ctx.cpu.regs.eax);",
            ),
            (
                [0xdd, 0x20],
                "ctx.cpu.fpu.restore(&ctx.memory, ctx.cpu.regs.eax);",
            ),
        ] {
            let mut decoder =
                iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
            let instr = crate::Instr {
                ip: crate::IP::Flat(0),
                iced: decoder.decode(),
                hint: None,
            };
            codegen.gen_instr(&instr).unwrap();
            assert!(codegen.buf.contains(want));
        }
    }

    #[test]
    fn codegen_handles_16_bit_fpu_environment() {
        let mut state = crate::State::default();
        state.module = crate::Module::DOS(crate::DOSModule::default());
        let mut codegen = super::CodeGen::new(&state, false);

        for (bytes, want, memory_size) in [
            ([0xd9, 0x30], "store_env16", iced_x86::MemorySize::FpuEnv14),
            ([0xd9, 0x20], "load_env16", iced_x86::MemorySize::FpuEnv14),
            ([0xdd, 0x30], "save16", iced_x86::MemorySize::FpuState94),
            ([0xdd, 0x20], "restore16", iced_x86::MemorySize::FpuState94),
        ] {
            let mut decoder =
                iced_x86::Decoder::with_ip(16, &bytes, 0, iced_x86::DecoderOptions::NONE);
            let instr = crate::Instr {
                ip: crate::IP::Seg((0, 0).into()),
                iced: decoder.decode(),
                hint: None,
            };
            assert_eq!(instr.iced.memory_size(), memory_size);
            codegen.gen_instr(&instr).unwrap();
            assert!(codegen.buf.contains(want));
        }
    }

    #[test]
    fn codegen_handles_fninit() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xdb, 0xe3];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("ctx.cpu.fpu.init();"));
    }

    #[test]
    fn codegen_handles_fptan() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd9, 0xf2];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.fpu.set(0, ctx.cpu.fpu.get(0).tan());")
        );
        assert!(codegen.buf.contains("ctx.cpu.fpu.push(1.0);"));
    }

    #[test]
    fn codegen_handles_fscale() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd9, 0xfd];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains(
            "ctx.cpu.fpu.set(0, ctx.cpu.fpu.get(0) * 2f64.powi(ctx.cpu.fpu.get(1).trunc() as i32));"
        ));
    }

    #[test]
    fn codegen_handles_fldl2e() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd9, 0xea];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.fpu.push(std::f64::consts::LOG2_E);")
        );
    }

    #[test]
    fn codegen_handles_fldpi() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd9, 0xeb];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.fpu.push(std::f64::consts::PI);")
        );
    }

    #[test]
    fn codegen_handles_fldlg2() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd9, 0xec];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.fpu.push(std::f64::consts::LOG10_2);")
        );
    }

    #[test]
    fn codegen_handles_frndint() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd9, 0xfc];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.fpu.set(0, ctx.cpu.fpu.round(ctx.cpu.fpu.get(0)));")
        );
    }

    #[test]
    fn codegen_handles_rdtsc() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x0f, 0x31];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("ctx.cpu.regs.set_edx_eax(rdtsc());"));
    }

    #[test]
    fn codegen_handles_ftst() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd9, 0xe4];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.fpu.compare(ctx.cpu.fpu.get(0), 0.0);")
        );
    }

    #[test]
    fn codegen_handles_fxam() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd9, 0xe5];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("ctx.cpu.fpu.examine();"));
    }

    #[test]
    fn codegen_handles_fyl2x() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd9, 0xf1];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("let t = ctx.cpu.fpu.get(1) * ctx.cpu.fpu.get(0).log2();")
        );
        assert_eq!(codegen.buf.matches("ctx.cpu.fpu.pop();").count(), 1);
        assert!(codegen.buf.contains("ctx.cpu.fpu.set(0, t);"));
    }

    #[test]
    fn codegen_handles_fcompp() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xde, 0xd9];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.fpu.compare(ctx.cpu.fpu.get(0), ctx.cpu.fpu.get(1));")
        );
        assert_eq!(codegen.buf.matches("ctx.cpu.fpu.pop();").count(), 2);
    }

    #[test]
    fn codegen_handles_fisub() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xda, 0x20];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains(
            "ctx.cpu.fpu.set(0, ctx.cpu.fpu.get(0) - ctx.memory.read::<u32>(ctx.cpu.regs.eax) as i32 as f64);"
        ));
    }

    #[test]
    fn codegen_handles_fiadd() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xda, 0x00];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains(
            "ctx.cpu.fpu.set(0, ctx.cpu.fpu.get(0) + ctx.memory.read::<u32>(ctx.cpu.regs.eax) as i32 as f64);"
        ));
    }

    #[test]
    fn codegen_handles_fidiv_and_fidivr() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);

        for (bytes, want) in [
            (
                &[0xda, 0x30][..],
                "ctx.cpu.fpu.set(0, ctx.cpu.fpu.get(0) / ctx.memory.read::<u32>(ctx.cpu.regs.eax) as i32 as f64);",
            ),
            (
                &[0xda, 0x38][..],
                "ctx.cpu.fpu.set(0, ctx.memory.read::<u32>(ctx.cpu.regs.eax) as i32 as f64 / ctx.cpu.fpu.get(0));",
            ),
        ] {
            let mut decoder =
                iced_x86::Decoder::with_ip(32, bytes, 0, iced_x86::DecoderOptions::NONE);
            let instr = crate::Instr {
                ip: crate::IP::Flat(0),
                iced: decoder.decode(),
                hint: None,
            };
            codegen.gen_instr(&instr).unwrap();
            assert!(codegen.buf.contains(want));
        }
    }

    #[test]
    fn codegen_maps_sal_to_shl() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd0, 0xe0];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("shl("));
    }

    #[test]
    fn codegen_handles_int1_as_a_continuation() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xf1];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("unhandled_interrupt"));
    }

    #[test]
    fn codegen_handles_int3_as_a_continuation() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xcc];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("unhandled_interrupt"));
    }

    #[test]
    fn codegen_handles_loope() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xe1, 0x00];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("ctx.loope("));
    }

    #[test]
    fn codegen_handles_into_overflow_trap() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xce];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("ctx.cpu.flags.contains(Flags::OF)"));
        assert!(codegen.buf.contains("unhandled_interrupt(0x4, 0x0);"));
        assert!(codegen.buf.contains("Cont(unk_1)"));
    }

    #[test]
    fn codegen_maps_windows_int_to_explicit_failure() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xcd, 0x06];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("unhandled_interrupt(0x6, 0x0);"));
        assert!(!codegen.buf.contains("todo!"));
    }

    #[test]
    fn codegen_handles_bswap() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x0f, 0xc8];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.regs.eax = bswap(ctx.cpu.regs.eax);")
        );
    }

    #[test]
    fn codegen_handles_aam() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd4, 0x0a];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("ctx.aam(0xau8);"));
    }

    #[test]
    fn codegen_handles_aad() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xd5, 0x0a];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("ctx.aad(0xau8);"));
    }

    #[test]
    fn codegen_handles_aas() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x3f];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("ctx.aas();"));
    }

    #[test]
    fn codegen_handles_aaa() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x37];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("ctx.aaa();"));
    }

    #[test]
    fn codegen_handles_das() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x2f];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("ctx.das();"));
    }

    #[test]
    fn codegen_handles_daa() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x27];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("ctx.daa();"));
    }

    #[test]
    fn codegen_handles_cmc() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0xf5];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("cmc(ctx);"));
    }

    #[test]
    fn codegen_handles_lahf() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x9f];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("lahf(ctx);"));
    }

    #[test]
    fn codegen_handles_pushf() {
        let mut state = crate::State::default();
        state.module = crate::Module::DOS(crate::DOSModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x9c];
        let mut decoder = iced_x86::Decoder::with_ip(16, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Seg((0, 0).into()),
            iced: decoder.decode(),
            hint: None,
        };

        assert_eq!(instr.iced.mnemonic(), iced_x86::Mnemonic::Pushf);
        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.push16(ctx.cpu.flags.bits() as u16 | 2);")
        );
    }

    #[test]
    fn codegen_handles_popf() {
        let mut state = crate::State::default();
        state.module = crate::Module::DOS(crate::DOSModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x9d];
        let mut decoder = iced_x86::Decoder::with_ip(16, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Seg((0, 0).into()),
            iced: decoder.decode(),
            hint: None,
        };

        assert_eq!(instr.iced.mnemonic(), iced_x86::Mnemonic::Popf);
        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.flags = Flags::from_bits_truncate(ctx.pop16() as u32 & !2);")
        );
    }

    #[test]
    fn codegen_handles_pushfd() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x9c];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.push32(ctx.cpu.flags.bits() | 2);")
        );
    }

    #[test]
    fn codegen_handles_popfd() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x9d];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("ctx.cpu.flags = Flags::from_bits_truncate(ctx.pop32() & !2);")
        );
    }

    #[test]
    fn codegen_handles_cpuid() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x0f, 0xa2];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(
            codegen
                .buf
                .contains("cpuid(ctx.cpu.regs.eax, ctx.cpu.regs.ecx)")
        );
        assert!(codegen.buf.contains("ctx.cpu.regs.edx = cpuid_edx;"));
    }

    #[test]
    fn codegen_handles_cmpxchg() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x0f, 0xb1, 0xc1];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("let cmpxchg_old = ctx.cpu.regs.ecx;"));
        assert!(
            codegen
                .buf
                .contains("sub(ctx.cpu.regs.eax, cmpxchg_old, &mut ctx.cpu.flags);")
        );
        assert!(codegen.buf.contains("ctx.cpu.regs.ecx = ctx.cpu.regs.eax;"));
        assert!(codegen.buf.contains("ctx.cpu.regs.eax = cmpxchg_old;"));
    }

    #[test]
    fn codegen_handles_all_setcc_conditions() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        for (opcode, condition) in [
            (0x90, "seto"),
            (0x91, "setno"),
            (0x98, "sets"),
            (0x99, "setns"),
            (0x9a, "setp"),
            (0x9b, "setnp"),
        ] {
            let mut codegen = super::CodeGen::new(&state, false);
            let bytes = [0x0f, opcode, 0xc0];
            let mut decoder =
                iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
            let instr = crate::Instr {
                ip: crate::IP::Flat(0),
                iced: decoder.decode(),
                hint: None,
            };

            codegen.gen_instr(&instr).unwrap();
            assert!(codegen.buf.contains(&format!("ctx.{condition}()")));
        }
    }

    #[test]
    fn codegen_handles_xgetbv() {
        let mut state = crate::State::default();
        state.module = crate::Module::Windows(crate::WindowsModule::default());
        let mut codegen = super::CodeGen::new(&state, false);
        let bytes = [0x0f, 0x01, 0xd0];
        let mut decoder = iced_x86::Decoder::with_ip(32, &bytes, 0, iced_x86::DecoderOptions::NONE);
        let instr = crate::Instr {
            ip: crate::IP::Flat(0),
            iced: decoder.decode(),
            hint: None,
        };

        codegen.gen_instr(&instr).unwrap();
        assert!(codegen.buf.contains("xgetbv(ctx.cpu.regs.ecx)"));
        assert!(codegen.buf.contains("ctx.cpu.regs.edx = xgetbv_edx;"));
    }
}

fn rustfmt(text: &str) -> Result<String> {
    use std::io::Write;
    // Stolen from https://github.com/microsoft/windows-rs/blob/master/crates/tools/lib/src/lib.rs
    let mut child = std::process::Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()?;
    let mut stdin = child.stdin.take().unwrap();
    stdin.write_all(text.as_bytes())?;
    drop(stdin);
    let output = child.wait_with_output()?;

    if !output.status.success() {
        bail!("rustfmt failed: {}", std::str::from_utf8(&output.stderr)?);
    }
    Ok(String::from_utf8(output.stdout)?)
}
